package com.palehorsestudios.alone;

import com.google.common.collect.ImmutableMap;
import com.palehorsestudios.alone.Foods.Food;
import com.palehorsestudios.alone.Foods.FoodFactory;
import com.palehorsestudios.alone.Items.Item;
import com.palehorsestudios.alone.Items.ItemFactory;
import com.palehorsestudios.alone.activity.*;
import com.palehorsestudios.alone.gui.GameApp;
import com.palehorsestudios.alone.player.Player;
import javafx.application.Application;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

public class Main {
    public static void main(String[] args) {
        Application.launch(GameApp.class, args);
    }

    public static Choice parseChoice(String input, Player player) {
        Choice choice;

        Map<String, String> choiceKeywordMap = new HashMap<>() {{
            put("eat moose", "eat");
            put("eat fish", "eat");
            put("eat squirrel", "eat");
            put("eat rabbit", "eat");
            put("eat porcupine", "eat");
            put("eat bug", "eat");
            put("eat bugs", "eat");
            put("eat mushroom", "eat");
            put("eat mushrooms", "eat");
            put("eat berry", "eat");
            put("eat berries", "eat");
            put("eat bear", "eat");
            put("go hunt", "hunt");
            put("go hunting", "hunt");
            put("hunt", "hunt");
            put("hunt moose", "hunt");
            put("hunt squirrel", "hunt");
            put("hunt rabbit", "hunt");
            put("hunt porcupine", "hunt");
            put("forage", "forage");
            put("go forage", "forage");
            put("go foraging", "forage");
            put("hunt bug", "forage");
            put("hunt mushrooms", "forage");
            put("hunt berry", "forage");
            put("hunt bugs", "forage");
            put("hunt mushroom", "forage");
            put("hunt berries", "forage");
            put("get moose", "hunt");
            put("get squirrel", "hunt");
            put("get rabbit", "hunt");
            put("get porcupine", "hunt");
            put("get bug", "forage");
            put("get mushrooms", "forage");
            put("get berry", "forage");
            put("get bugs", "forage");
            put("get mushroom", "forage");
            put("get berries", "forage");
            put("kill moose", "hunt");
            put("kill squirrel", "hunt");
            put("kill rabbit", "hunt");
            put("kill porcupine", "hunt");
            put("kill bug", "forage");
            put("kill mushrooms", "forage");
            put("kill berry", "forage");
            put("kill bugs", "forage");
            put("kill mushroom", "forage");
            put("kill berries", "forage");
            put("trap squirrel", "trap");
            put("trap moose", "trap");
            put("trap rabbit", "trap");
            put("trap porcupine", "trap");
            put("trap", "trap");
            put("trapping", "trap");
            put("go trap", "trap");
            put("go trapping", "trap");
            put("fish", "fish");
            put("fishing", "fish");
            put("go fish", "fish");
            put("go fishing", "fish");
            put("get fishing line", "get");
            put("get fishing lines", "get");
            put("get fishing hooks", "get");
            put("get fishing hook", "get");
            put("get fishing lure", "get");
            put("get fishing lures", "get");
            put("get knife", "get");
            put("get flint and steel", "get");
            put("get bow", "get");
            put("get arrow", "get");
            put("get arrows", "get");
            put("get family photo", "get");
            put("get photo", "get");
            put("get photograph", "get");
            put("get rope", "get");
            put("get parachute chord", "get");
            put("get cordage", "get");
            put("get flare", "get");
            put("get flares", "get");
            put("get extra boots", "get");
            put("get extra boot", "get");
            put("get boots", "get");
            put("get boot", "get");
            put("get extra pants", "get");
            put("get pants", "get");
            put("get sleeping gear", "get");
            put("get sleeping bag", "get");
            put("get cold weather gear", "get");
            put("get cold gear", "get");
            put("get tarp", "get");
            put("get matches", "get");
            put("get match", "get");
            put("get first aid", "get");
            put("get first aid kit", "get");
            put("get flashlight", "get");
            put("get light", "get");
            put("get batteries", "get");
            put("get battery", "get");
            put("get wire", "get");
            put("get 18 gauge wire", "get");
            put("get wires", "get");
            put("get 18 gauge wires", "get");
            put("get snare", "get");
            put("get pot", "get");
            put("get cooking pot", "get");
            put("get axe", "get");
            put("get hatchet", "get");
            put("get iodine tablets", "get");
            put("get iodine", "get");
            put("get tablets", "get");
            put("get pistol", "get");
            put("get gun", "get");
            put("get ammunition", "get");
            put("get cartridges", "get");
            put("get ammo", "get");
            put("get rounds", "get");
            put("get shovel", "get");
            put("get harmonica", "get");
            put("get lighter", "get");
            put("get survival manual", "get");
            put("get manual", "get");
            put("get journal and pen", "get");
            put("get journal", "get");
            put("put fishing line", "put");
            put("put fishing lines", "put");
            put("put fishing hooks", "put");
            put("put fishing hook", "put");
            put("put fishing lure", "put");
            put("put fishing lures", "put");
            put("put knife", "put");
            put("put flint and steel", "put");
            put("put bow", "put");
            put("put arrow", "put");
            put("put arrows", "put");
            put("put family photo", "put");
            put("put photo", "put");
            put("put photograph", "put");
            put("put rope", "put");
            put("put parachute chord", "put");
            put("put cordage", "put");
            put("put flare", "put");
            put("put flares", "put");
            put("put extra boots", "put");
            put("put extra boot", "put");
            put("put boots", "put");
            put("put boot", "put");
            put("put extra pants", "put");
            put("put pants", "put");
            put("put sleeping gear", "put");
            put("put sleeping bag", "put");
            put("put cold weather gear", "put");
            put("put cold gear", "put");
            put("put tarp", "put");
            put("put matches", "put");
            put("put match", "put");
            put("put first aid", "put");
            put("put first aid kit", "put");
            put("put flashlight", "put");
            put("put light", "put");
            put("put batteries", "put");
            put("put battery", "put");
            put("put wire", "put");
            put("put 18 gauge wire", "put");
            put("put wires", "put");
            put("put 18 gauge wires", "put");
            put("put snare", "put");
            put("put pot", "put");
            put("put cooking pot", "put");
            put("put axe", "put");
            put("put hatchet", "put");
            put("put iodine tablets", "put");
            put("put iodine", "put");
            put("put tablets", "put");
            put("put pistol", "put");
            put("put gun", "put");
            put("put ammunition", "put");
            put("put ammo", "put");
            put("put cartridges", "put");
            put("put rounds", "put");
            put("put shovel", "put");
            put("put harmonica", "put");
            put("put lighter", "put");
            put("put survival manual", "put");
            put("put manual", "put");
            put("put journal and pen", "put");
            put("put journal", "put");
            put("build shelter", "improve");
            put("make camp", "improve");
            put("work on camp", "improve");
            put("work on shelter", "improve");
            put("improve shelter", "improve");
            put("improve camp", "improve");
            put("build camp", "improve");
            put("drink", "drink");
            put("drink water", "drink");
            put("get drink", "drink");
            put("take drink", "drink");
            put("get a drink", "drink");
            put("take a drink", "drink");
            put("gather", "gather");
            put("gather firewood", "gather");
            put("get firewood", "gather");
            put("collect firewood", "gather");
            put("cut firewood", "gather");
            put("gather wood", "gather");
            put("get wood", "gather");
            put("collect wood", "gather");
            put("cut wood", "gather");
            put("fire", "fire");
            put("build fire", "fire");
            put("light fire", "fire");
            put("start fire", "fire");
            put("make fire", "fire");
            put("build a fire", "fire");
            put("light a fire", "fire");
            put("start a fire", "fire");
            put("make a fire", "fire");
            put("water", "water");
            put("get water", "water");
            put("fetch water", "water");
            put("collect water", "water");
            put("morale", "morale");
            put("improve morale", "morale");
            put("boost morale", "morale");
            put("photo", "morale");
            put("look at photo", "morale");
            put("look at family photo", "morale");
            put("harmonica", "morale");
            put("play harmonica", "morale");
            put("journal", "morale");
            put("write in journal", "morale");
            put("rest", "rest");
            put("break", "rest");
            put("take rest", "rest");
            put("take break", "rest");
            put("take a rest", "rest");
            put("take a break", "rest");
            put("relax", "rest");
            put("nap", "rest");
            put("take nap", "rest");
            put("take a nap", "rest");
        }};
        Map<String, Food> choiceFoodMap = new HashMap<>() {{
            put("eat moose", FoodFactory.getNewInstance("Moose"));
            put("eat fish", FoodFactory.getNewInstance("Fish"));
            put("eat bear", FoodFactory.getNewInstance("Bear"));
            put("eat squirrel", FoodFactory.getNewInstance("Squirrel"));
            put("eat rabbit", FoodFactory.getNewInstance("Rabbit"));
            put("eat porcupine", FoodFactory.getNewInstance("Porcupine"));
            put("eat bug", FoodFactory.getNewInstance("Bug"));
            put("eat bugs", FoodFactory.getNewInstance("Bug"));
            put("eat mushroom", FoodFactory.getNewInstance("Mushroom"));
            put("eat mushrooms", FoodFactory.getNewInstance("Mushroom"));
            put("eat berry", FoodFactory.getNewInstance("Berries"));
            put("eat berries", FoodFactory.getNewInstance("Berries"));
        }};
        Map<String, Item> choiceItemMap = new HashMap<>() {{
            put("get fishing line", ItemFactory.getNewInstance("Fishing Line"));
            put("get fishing lines", ItemFactory.getNewInstance("Fishing Line"));
            put("get fishing hooks", ItemFactory.getNewInstance("Fishing Hooks"));
            put("get fishing hook", ItemFactory.getNewInstance("Fishing Hooks"));
            put("get fishing lure", ItemFactory.getNewInstance("Fishing Lures"));
            put("get fishing lures", ItemFactory.getNewInstance("Fishing Lures"));
            put("get knife", ItemFactory.getNewInstance("Knife"));
            put("get flint and steel", ItemFactory.getNewInstance("Flint and Steel"));
            put("get bow", ItemFactory.getNewInstance("Bow"));
            put("get arrow", ItemFactory.getNewInstance("Arrow"));
            put("get arrows", ItemFactory.getNewInstance("Arrow"));
            put("get family photo", ItemFactory.getNewInstance("Family Photo"));
            put("get photo", ItemFactory.getNewInstance("Family Photo"));
            put("get photograph", ItemFactory.getNewInstance("Family Photo"));
            put("get rope", ItemFactory.getNewInstance("Parachute Chord"));
            put("get parachute chord", ItemFactory.getNewInstance("Parachute Chord"));
            put("get cordage", ItemFactory.getNewInstance("Parachute Chord"));
            put("get flare", ItemFactory.getNewInstance("Flare"));
            put("get flares", ItemFactory.getNewInstance("Flare"));
            put("get extra boots", ItemFactory.getNewInstance("Boots"));
            put("get extra boot", ItemFactory.getNewInstance("Boots"));
            put("get boots", ItemFactory.getNewInstance("Boots"));
            put("get boot", ItemFactory.getNewInstance("Boots"));
            put("get extra pants", ItemFactory.getNewInstance("Pants"));
            put("get pants", ItemFactory.getNewInstance("Pants"));
            put("get sleeping gear", ItemFactory.getNewInstance("Sleeping Gear"));
            put("get sleeping bag", ItemFactory.getNewInstance("Sleeping Gear"));
            put("get cold weather gear", ItemFactory.getNewInstance("Cold Weather Gear"));
            put("get cold gear", ItemFactory.getNewInstance("Cold Weather Gear"));
            put("get tarp", ItemFactory.getNewInstance("Tarp"));
            put("get matches", ItemFactory.getNewInstance("Matches"));
            put("get match", ItemFactory.getNewInstance("Matches"));
            put("get first aid", ItemFactory.getNewInstance("First Aid Kit"));
            put("get first aid kit", ItemFactory.getNewInstance("First Aid Kit"));
            put("get flashlight", ItemFactory.getNewInstance("Flashlight"));
            put("get light", ItemFactory.getNewInstance("Flashlight"));
            put("get batteries", ItemFactory.getNewInstance("Batteries"));
            put("get battery", ItemFactory.getNewInstance("Batteries"));
            put("get wire", ItemFactory.getNewInstance("Wire"));
            put("get 18 gauge wire", ItemFactory.getNewInstance("Wire"));
            put("get wires", ItemFactory.getNewInstance("Wire"));
            put("get 18 gauge wires", ItemFactory.getNewInstance("Wire"));
            put("get snare", ItemFactory.getNewInstance("Wire"));
            put("get pot", ItemFactory.getNewInstance("Pot"));
            put("get cooking pot", ItemFactory.getNewInstance("Pot"));
            put("get axe", ItemFactory.getNewInstance("Axe"));
            put("get hatchet", ItemFactory.getNewInstance("Hatchet"));
            put("get iodine tablets", ItemFactory.getNewInstance("Iodine Tablets"));
            put("get iodine", ItemFactory.getNewInstance("Iodine Tablets"));
            put("get tablets", ItemFactory.getNewInstance("Iodine Tablets"));
            put("get pistol", ItemFactory.getNewInstance("Pistol"));
            put("get gun", ItemFactory.getNewInstance("Pistol"));
            put("get ammunition", ItemFactory.getNewInstance("Pistol Cartridge"));
            put("get cartridges", ItemFactory.getNewInstance("Pistol Cartridge"));
            put("get ammo", ItemFactory.getNewInstance("Pistol Cartridge"));
            put("get rounds", ItemFactory.getNewInstance("Pistol Cartridge"));
            put("get pistol ammo", ItemFactory.getNewInstance("Pistol Cartridge"));
            put("get pistol ammunition", ItemFactory.getNewInstance("Pistol Cartridge"));
            put("get pistol rounds", ItemFactory.getNewInstance("Pistol Cartridge"));
            put("get pistol cartridges", ItemFactory.getNewInstance("Pistol Cartridge"));
            put("get shovel", ItemFactory.getNewInstance("Shovel"));
            put("get harmonica", ItemFactory.getNewInstance("Harmonica"));
            put("get lighter", ItemFactory.getNewInstance("Lighter"));
            put("get survival manual", ItemFactory.getNewInstance("Survival Manual"));
            put("get manual", ItemFactory.getNewInstance("Survival Manual"));
            put("get journal and pen", ItemFactory.getNewInstance("Journal"));
            put("get journal", ItemFactory.getNewInstance("Journal"));
            put("put fishing line", ItemFactory.getNewInstance("Fishing Line"));
            put("put fishing lines", ItemFactory.getNewInstance("Fishing Line"));
            put("put fishing hooks", ItemFactory.getNewInstance("Fishing Hooks"));
            put("put fishing hook", ItemFactory.getNewInstance("Fishing Hooks"));
            put("put fishing lure", ItemFactory.getNewInstance("Fishing Lures"));
            put("put fishing lures", ItemFactory.getNewInstance("Fishing Lures"));
            put("put knife", ItemFactory.getNewInstance("Knife"));
            put("put flint and steel", ItemFactory.getNewInstance("Flint and Steel"));
            put("put bow", ItemFactory.getNewInstance("Bow"));
            put("put arrow", ItemFactory.getNewInstance("Arrow"));
            put("put arrows", ItemFactory.getNewInstance("Arrow"));
            put("put family photo", ItemFactory.getNewInstance("Family Photo"));
            put("put photo", ItemFactory.getNewInstance("Family Photo"));
            put("put photograph", ItemFactory.getNewInstance("Family Photo"));
            put("put rope", ItemFactory.getNewInstance("Parachute Chord"));
            put("put parachute chord", ItemFactory.getNewInstance("Parachute Chord"));
            put("put cordage", ItemFactory.getNewInstance("Parachute Chord"));
            put("put flare", ItemFactory.getNewInstance("Flare"));
            put("put flares", ItemFactory.getNewInstance("Flare"));
            put("put extra boots", ItemFactory.getNewInstance("Boots"));
            put("put extra boot", ItemFactory.getNewInstance("Boots"));
            put("put boots", ItemFactory.getNewInstance("Boots"));
            put("put boot", ItemFactory.getNewInstance("Boots"));
            put("put extra pants", ItemFactory.getNewInstance("Pants"));
            put("put pants", ItemFactory.getNewInstance("Pants"));
            put("put sleeping gear", ItemFactory.getNewInstance("Sleeping Gear"));
            put("put sleeping bag", ItemFactory.getNewInstance("Sleeping Gear"));
            put("put cold weather gear", ItemFactory.getNewInstance("Cold Weather Gear"));
            put("put cold gear", ItemFactory.getNewInstance("Cold Weather Gear"));
            put("put tarp", ItemFactory.getNewInstance("Tarp"));
            put("put matches", ItemFactory.getNewInstance("Matches"));
            put("put match", ItemFactory.getNewInstance("Matches"));
            put("put first aid", ItemFactory.getNewInstance("First Aid Kit"));
            put("put first aid kit", ItemFactory.getNewInstance("First Aid Kit"));
            put("put flashlight", ItemFactory.getNewInstance("Flashlight"));
            put("put light", ItemFactory.getNewInstance("Flashlight"));
            put("put batteries", ItemFactory.getNewInstance("Batteries"));
            put("put battery", ItemFactory.getNewInstance("Batteries"));
            put("put wire", ItemFactory.getNewInstance("Wire"));
            put("put 18 gauge wire", ItemFactory.getNewInstance("Wire"));
            put("put wires", ItemFactory.getNewInstance("Wire"));
            put("put 18 gauge wires", ItemFactory.getNewInstance("Wire"));
            put("put snare", ItemFactory.getNewInstance("Wire"));
            put("put pot", ItemFactory.getNewInstance("Pot"));
            put("put cooking pot", ItemFactory.getNewInstance("Pot"));
            put("put axe", ItemFactory.getNewInstance("Axe"));
            put("put hatchet", ItemFactory.getNewInstance("Hatchet"));
            put("put iodine tablets", ItemFactory.getNewInstance("Iodine Tablets"));
            put("put iodine", ItemFactory.getNewInstance("Iodine Tablets"));
            put("put tablets", ItemFactory.getNewInstance("Iodine Tablets"));
            put("put pistol", ItemFactory.getNewInstance("Pistol"));
            put("put gun", ItemFactory.getNewInstance("Pistol"));
            put("put ammunition", ItemFactory.getNewInstance("Pistol Cartridge"));
            put("put ammo", ItemFactory.getNewInstance("Pistol Cartridge"));
            put("put pistol ammo", ItemFactory.getNewInstance("Pistol Cartridge"));
            put("put pistol ammunition", ItemFactory.getNewInstance("Pistol Cartridge"));
            put("put pistol rounds", ItemFactory.getNewInstance("Pistol Cartridge"));
            put("put pistol cartridges", ItemFactory.getNewInstance("Pistol Cartridge"));
            put("put cartridges", ItemFactory.getNewInstance("Pistol Cartridge"));
            put("put rounds", ItemFactory.getNewInstance("Pistol Cartridge"));
            put("put shovel", ItemFactory.getNewInstance("Shovel"));
            put("put harmonica", ItemFactory.getNewInstance("Harmonica"));
            put("put lighter", ItemFactory.getNewInstance("Lighter"));
            put("put survival manual", ItemFactory.getNewInstance("Survival Manual"));
            put("put manual", ItemFactory.getNewInstance("Survival Manual"));
            put("put journal and pen", ItemFactory.getNewInstance("Journal"));
            put("put journal", ItemFactory.getNewInstance("Journal"));
            put("put waterproof bag", ItemFactory.getNewInstance("Waterproof Bag"));
        }};

        // uses input to build a choice by looking up keywords in a choice map
        // split up input into array of words
        String keyword;
        Food food;
        Item item;
        if (Optional.ofNullable(choiceKeywordMap.get(input.toLowerCase())).isPresent()) {
            keyword = Optional.ofNullable(choiceKeywordMap.get(input.toLowerCase())).get();
            if (keyword.equals("eat")) {
                if (Optional.ofNullable(choiceFoodMap.get(input.toLowerCase())).isPresent()) {
                    food = Optional.ofNullable(choiceFoodMap.get(input.toLowerCase())).get();
                    choice = new Choice(keyword, player, food);
                } else {
                    choice = new Choice(keyword, player);
                }
            } else if (keyword.equals("get") || keyword.equals("put")) {
                if (Optional.ofNullable(choiceItemMap.get(input.toLowerCase())).isPresent()) {
                    item = Optional.ofNullable(choiceItemMap.get(input.toLowerCase())).get();
                    choice = new Choice(keyword, player, item);
                } else {
                    choice = null;
                }
            } else {
                choice = new Choice(keyword, player);
            }
        } else {
            choice = null;
        }
        return choice;
    }

    public static Activity parseActivityChoice(Choice choice) {
        Map<String, Activity> options = new HashMap<>() {{
                put("get", GetItemActivity.getInstance());
                put("put", PutItemActivity.getInstance());
                put("eat", EatActivity.getInstance());
                put("drink", DrinkWaterActivity.getInstance());
                put("fish", FishActivity.getInstance());
                put("hunt", HuntActivity.getInstance());
                put("trap", TrapActivity.getInstance());
                put("forage", ForageActivity.getInstance());
                put("improve", ImproveShelterActivity.getInstance());
                put("gather", GatherFirewoodActivity.getInstance());
                put("fire", BuildFireActivity.getInstance());
                put("water", GetWaterActivity.getInstance());
                put("morale", BoostMoraleActivity.getInstance());
                put("craft", CraftActivity.getInstance());
        }};

        if (choice == null) {
            return null;
        } else {
            return Objects.requireNonNullElse(options.get(choice.getKeyword()), RestActivity.getInstance());
        }

    }

}
